### ISSUE TITLE
Code Inspection: Tslint on hover

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#116]
### no-duplicate-imports

- [`lib/page/sunburstScript.ts:18`](https://github.com/atomist-blogs/org-visualizer/blob/a5e0eb8a8474d151e315165535db6c8dcdb5fcc7/lib/page/sunburstScript.ts#L18): _(error)_ Multiple imports from 'd3' can be combined into one.

[atomist:code-inspection:hover=@atomist/atomist-sdm]

**Comment by dansmithy** [comment]
Issue closed because branch `hover` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `hover` was deleted.
