### ISSUE TITLE
Code Inspection: Tslint on up-master

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#12]
### await-promise

- [`lib/setIdeals.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/setIdeals.ts#L45): _(error)_ Invalid 'await' of a non-Promise value.

### no-console

- [`lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts:127`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts#L127): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/feature/domain/TsLintFeature.ts:54`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TsLintFeature.ts#L54): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/feature/featureQueries.ts:68`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/featureQueries.ts#L68): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/routes/features.ts:109`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/routes/features.ts#L109): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/routes/orgPage.ts:247`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/routes/orgPage.ts#L247): _(warn)_ Calls to 'console.log' are not allowed.

### no-floating-promises

- [`lib/setIdeals.ts:49`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/setIdeals.ts#L49): _(error)_ Promises must be handled appropriately

### no-implicit-dependencies

- [`lib/analysis/offline/spider/github/GitHubSpider.ts:31`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/analysis/offline/spider/github/GitHubSpider.ts#L31): _(error)_ Module '@octokit/request' is not listed as dependency in package.json

### no-object-literal-type-assertion

- [`lib/routes/orgPage.ts:194`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/routes/orgPage.ts#L194): _(error)_ Type assertion on object literals is forbidden, use a type annotation instead.
- [`test/spider/github/GithubSpider.test.ts:58`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L58): _(error)_ Type assertion on object literals is forbidden, use a type annotation instead.

### no-shadowed-variable

- [`lib/feature/featureQueries.ts:46`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/featureQueries.ts#L46): _(error)_ Shadowed name: 'fp'
- [`lib/feature/featureQueries.ts:66`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/featureQueries.ts#L66): _(error)_ Shadowed name: 'fp'

### no-var-requires

- [`lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts:35`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts#L35): _(error)_ require statement not part of an import statement
- [`lib/machine/gitActivityScanner.ts:24`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/machine/gitActivityScanner.ts#L24): _(error)_ require statement not part of an import statement

### ordered-imports

- [`lib/feature/featureQueries.ts:19`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/featureQueries.ts#L19): _(error)_ Import sources within a group must be alphabetized.
- [`lib/routes/wellKnownQueries.ts:42`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/routes/wellKnownQueries.ts#L42): _(error)_ Import sources within a group must be alphabetized.

### radix

- [`lib/machine/gitActivityScanner.ts:39`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/machine/gitActivityScanner.ts#L39): _(error)_ Missing radix parameter

### triple-equals

- [`lib/element/codeOfConduct.ts:64`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/element/codeOfConduct.ts#L64): _(error)_ == should be ===

### typedef

- [`lib/feature/domain/TsLintFeature.ts:32`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TsLintFeature.ts#L32): _(error)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:34`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TsLintFeature.ts#L34): _(error)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:36`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TsLintFeature.ts#L36): _(error)_ expected call-signature: 'apply' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:42`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TsLintFeature.ts#L42): _(error)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:44`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TsLintFeature.ts#L44): _(error)_ expected member-variable-declaration: 'p' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:79`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TsLintFeature.ts#L79): _(error)_ expected parameter: 'path' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:33`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TypeScriptVersionFeature.ts#L33): _(error)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:35`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TypeScriptVersionFeature.ts#L35): _(error)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:37`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TypeScriptVersionFeature.ts#L37): _(error)_ expected call-signature: 'apply' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:43`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TypeScriptVersionFeature.ts#L43): _(error)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TypeScriptVersionFeature.ts#L45): _(error)_ expected call-signature: 'derive' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:55`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TypeScriptVersionFeature.ts#L55): _(error)_ expected call-signature: 'relevanceTest' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:59`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/feature/domain/TypeScriptVersionFeature.ts#L59): _(error)_ expected call-signature: 'necessityTest' to have a typedef
- [`lib/setIdeals.ts:28`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/setIdeals.ts#L28): _(error)_ expected call-signature: 'setIdeals' to have a typedef
- [`lib/tree/partitioner.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/lib/tree/partitioner.ts#L45): _(error)_ expected call-signature: 'rate' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/5d5c7899a98745b5a54b55822953740e9fae3554/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected parameter: 'q' to have a typedef

[atomist:code-inspection:up-master=@atomist/atomist-sdm]

**Comment by whostolebenfrog** [comment]
Issue closed because branch `up-master` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `up-master` was deleted.
