### ISSUE TITLE
Return names in the technology-native format

### ISSUE THREAD

**Issue by jrday** [atomist-blogs/org-visualizer#121]
For example:

/api/v1/[workspace_id]/filter/skew?type=npm-project-deps

returns package names that are not in npm notation:

`"name": "atomist::slack-messages"`

should be `@atomist/slack-messages`

Similarly with other dependency name notation.

**Comment by johnsonr** [comment]
Agree, this looks odd. @slimslenderslacks, @cdupuis we need to discuss name escaping at all levels.

**Comment by johnsonr** [comment]
Correct current URL for this is

/api/v1/[workspace_id]/drift?type=npm-project-deps

It does still exhibit the problem
