### ISSUE TITLE
Must be able to click through to repo on GitHub from sunburst page

### ISSUE THREAD

**Issue by johnsonr** [atomist-blogs/org-visualizer#124]
onClick in sunburst or link in details on right

**Comment by jessitron** [comment]
not onClick in sunburst; that already has meaning. Link in details on right, yes

**Comment by jessitron** [comment]
done. Click on the repo, and then the link appears on the right.
there is a flaw that if you hover over the middle it goes away, but that's a bug in how we're using d3 or something, and the correct fix for it is "make this a real react app."
