### ISSUE TITLE
Dependencies and package-versions

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-blogs/org-visualizer#126]
We are rendering the number of "dependencies" (the total number of rows for a particular Aspect), and also package versions (the total number of distinct Fingerprints across the entire Aspect).

The latter is not available from org-viz but is equivalent to the count of fingerprints for a particular Aspect across all HEAD commits in the workspace.

<img width="1841" alt="Screen Shot 2019-07-30 at 12 53 22" src="https://user-images.githubusercontent.com/1643888/62163675-b370cf80-b2cf-11e9-8e77-ce957647a5fa.png">

It would make sense to have this data available as a sibling to the `list` property in the /workspace/fingerprints/{aspect} endpoint.

**Comment by cdupuis** [comment]
I'll add that.

**Comment by slimslenderslacks** [comment]
HEAD commits on default branch

**Comment by cdupuis** [comment]
I don't think org-viz has knowledge about what the default branch is.

**Comment by slimslenderslacks** [comment]
the backend data is looking at default branch but there is one open issue where we've got some repos without "master" branches and where github is return nil for the default branch.
