### ISSUE TITLE
Code Inspection: Tslint on explorer

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#131]
### max-line-length

- [`views/sunburstPage.tsx:104`](https://github.com/atomist-blogs/org-visualizer/blob/dc73d0d5fe49510ad616076987e5607a961200de/views/sunburstPage.tsx#L104): _(warn)_ Exceeds maximum line length of 150

[atomist:code-inspection:explorer=@atomist/atomist-sdm]

**Comment by cdupuis** [comment]
Issue closed because branch `explorer` was deleted.

**Comment by dansmithy** [comment]
Issue closed because branch `explorer` was deleted.
