### ISSUE TITLE
Include workspace in repository page(s) links

### ISSUE THREAD

**Issue by johnsonr** [atomist-blogs/org-visualizer#153]

**Comment by jessitron** [comment]
currently I only see workspace in the API URLs.
Where should it be?

**Comment by johnsonr** [comment]
Ah, good point. Maybe we should just hardcode it to `*` in the API call, which is pretty much what we have now

**Comment by jessitron** [comment]
makes sense

**Comment by johnsonr** [comment]
Not a bug
