### ISSUE TITLE
Code Inspection: Tslint on nortissej/log-at-debug

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#154]
### no-null-keyword

- [`views/repository.tsx:49`](https://github.com/atomist-blogs/org-visualizer/blob/8c9b2a2e016ab86ef235a364c3d1c0543be12f37/views/repository.tsx#L49): _(warn)_ Use 'undefined' instead of 'null'

[atomist:code-inspection:nortissej/log-at-debug=@atomist/atomist-sdm]

**Comment by dansmithy** [comment]
Issue closed because branch `nortissej/log-at-debug` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `nortissej/log-at-debug` was deleted.
