### ISSUE TITLE
Move spider cli command to CommandHandler

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#156]
To support the code split and to get rid of the global `npm link`, we need to move the spider cli command to be a normal command handler that gets invoked via `atomist analyze` with sdm-local.

Additionally that would allow us to kill the duplication around the global `Aspect` const. This could then all be properly wired up using the SDM configuration.

The global linking won't work when we move to an extension pack model where users include the org-viz code via an sdm extension pack in their own SDM.

**Comment by johnsonr** [comment]
Spidering can take many minutes with a large organization. Is that OK? Will it run in the new job support?

**Comment by cdupuis** [comment]
Many minutes is not a problem in local mode. I’m just not sure about log output. But I’m sure we can make that work somehow. 

Job support won’t work as that requires the backend. But we are running in local mode.
