### ISSUE TITLE
Code Inspection: Tslint on api

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#19]
### align

- [`lib/routes/orgPage.ts:69`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/orgPage.ts#L69): _(error)_ parameters are not aligned
- [`lib/routes/orgPage.ts:70`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/orgPage.ts#L70): _(error)_ parameters are not aligned

### await-promise

- [`lib/feature/reportersAgainst.ts:82`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L82): _(error)_ Invalid 'await' of a non-Promise value.
- [`lib/setIdeals.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/setIdeals.ts#L45): _(error)_ Invalid 'await' of a non-Promise value.

### comment-format

- [`lib/tree/sunburst.ts:64`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/tree/sunburst.ts#L64): _(error)_ comment must start with a space
- [`lib/tree/sunburst.ts:78`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/tree/sunburst.ts#L78): _(error)_ comment must start with a space

### eofline

- [`lib/api/reporting.ts:129`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L129): _(error)_ file should end with a newline
- [`lib/feature/reporters.ts:57`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reporters.ts#L57): _(error)_ file should end with a newline
- [`lib/tree/sunburst.ts:80`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/tree/sunburst.ts#L80): _(error)_ file should end with a newline

### no-consecutive-blank-lines

- [`test/tree/treeMerge.test.ts:37`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L37): _(error)_ Consecutive blank lines are forbidden

### no-console

- [`lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts:127`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts#L127): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/api/reporting.ts:74`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L74): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/api/reporting.ts:110`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L110): _(warn)_ Calls to 'console.log' are not allowed.
- [`test/reporting.test.ts:38`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/reporting.test.ts#L38): _(warn)_ Calls to 'console.log' are not allowed.

### no-empty-interface

- [`views/sunburstQuery.tsx:3`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/views/sunburstQuery.tsx#L3): _(error)_ An empty interface is equivalent to `{}`.

### no-floating-promises

- [`lib/setIdeals.ts:49`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/setIdeals.ts#L49): _(error)_ Promises must be handled appropriately

### no-implicit-dependencies

- [`lib/analysis/offline/spider/github/GitHubSpider.ts:31`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/analysis/offline/spider/github/GitHubSpider.ts#L31): _(error)_ Module '@octokit/request' is not listed as dependency in package.json

### no-object-literal-type-assertion

- [`lib/routes/orgPage.ts:189`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/orgPage.ts#L189): _(error)_ Type assertion on object literals is forbidden, use a type annotation instead.
- [`test/spider/github/GithubSpider.test.ts:58`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L58): _(error)_ Type assertion on object literals is forbidden, use a type annotation instead.

### no-shadowed-variable

- [`lib/api/reporting.ts:100`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L100): _(error)_ Shadowed name: 'runReports'
- [`lib/feature/reportersAgainst.ts:50`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L50): _(error)_ Shadowed name: 'featureManager'
- [`lib/feature/reportersAgainst.ts:97`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L97): _(error)_ Shadowed name: 'featureManager'
- [`lib/feature/reportersAgainst.ts:105`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L105): _(error)_ Shadowed name: 'featureManager'
- [`lib/feature/reportersAgainst.ts:118`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L118): _(error)_ Shadowed name: 'featureManager'
- [`lib/feature/reportersAgainst.ts:142`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L142): _(error)_ Shadowed name: 'featureManager'
- [`lib/routes/orgPage.ts:192`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/orgPage.ts#L192): _(error)_ Shadowed name: 'displayIdeal'

### no-unnecessary-callback-wrapper

- [`lib/routes/features.ts:147`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/features.ts#L147): _(error)_ No need to wrap 'parseInt' in another function. Just use it directly.
- [`lib/tree/sunburst.ts:46`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/tree/sunburst.ts#L46): _(error)_ No need to wrap 'merge2Trees' in another function. Just use it directly.

### no-var-requires

- [`lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts:35`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts#L35): _(error)_ require statement not part of an import statement

### object-literal-shorthand

- [`lib/routes/wellKnownReporters.ts:102`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/wellKnownReporters.ts#L102): _(error)_ Expected method shorthand in object literal ('{async *mapping() {...}}').
- [`test/tree/treeBuilder.test.ts:68`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeBuilder.test.ts#L68): _(error)_ Expected method shorthand in object literal ('{async *mapping() {...}}').

### ordered-imports

- [`lib/api/reporting.ts:29`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L29): _(error)_ Import sources within a group must be alphabetized.
- [`lib/feature/domain/assembledFeature.ts:18`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/assembledFeature.ts#L18): _(error)_ Import sources within a group must be alphabetized.
- [`lib/feature/domain/oneOf.ts:19`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/oneOf.ts#L19): _(error)_ Import sources within a group must be alphabetized.
- [`lib/feature/reportersAgainst.ts:39`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L39): _(error)_ Import sources within a group must be alphabetized.
- [`lib/routes/features.ts:44`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/features.ts#L44): _(error)_ Import sources within a group must be alphabetized.
- [`lib/routes/wellKnownReporters.ts:41`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/wellKnownReporters.ts#L41): _(error)_ Import sources within a group must be alphabetized.
- [`lib/routes/wellKnownReporters.ts:46`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/wellKnownReporters.ts#L46): _(error)_ Import sources within a group must be alphabetized.
- [`test/reporting.test.ts:22`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/reporting.test.ts#L22): _(error)_ Import sources within a group must be alphabetized.
- [`test/reporting.test.ts:23`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/reporting.test.ts#L23): _(error)_ Import sources within a group must be alphabetized.
- [`test/tree/treeMerge.test.ts:21`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L21): _(error)_ Import sources within a group must be alphabetized.

### radix

- [`lib/routes/features.ts:147`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/features.ts#L147): _(error)_ Missing radix parameter

### semicolon

- [`lib/api/reporting.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L123): _(error)_ Missing semicolon
- [`lib/feature/FeatureManager.ts:206`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/FeatureManager.ts#L206): _(error)_ Missing semicolon
- [`lib/feature/reportersAgainst.ts:102`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L102): _(error)_ Missing semicolon
- [`lib/routes/features.ts:152`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/features.ts#L152): _(error)_ Missing semicolon
- [`test/tree/treeBuilder.test.ts:69`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeBuilder.test.ts#L69): _(error)_ Missing semicolon

### trailing-comma

- [`lib/api/reporting.ts:124`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L124): _(error)_ Missing trailing comma
- [`lib/feature/DefaultFeatureManager.ts:202`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/DefaultFeatureManager.ts#L202): _(error)_ Missing trailing comma
- [`lib/feature/reportersAgainst.ts:61`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L61): _(error)_ Missing trailing comma
- [`lib/feature/reportersAgainst.ts:72`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L72): _(error)_ Missing trailing comma
- [`lib/feature/reportersAgainst.ts:78`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/reportersAgainst.ts#L78): _(error)_ Missing trailing comma
- [`lib/routes/features.ts:160`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/features.ts#L160): _(error)_ Missing trailing comma
- [`lib/routes/wellKnownReporters.ts:117`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/wellKnownReporters.ts#L117): _(error)_ Missing trailing comma
- [`lib/tree/TreeBuilder.ts:197`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/tree/TreeBuilder.ts#L197): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L45): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:54`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L54): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:67`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L67): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:82`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L82): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:91`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L91): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:93`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L93): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:94`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L94): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:105`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L105): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:114`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L114): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:116`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L116): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:132`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L132): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:145`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L145): _(error)_ Missing trailing comma
- [`test/tree/treeMerge.test.ts:147`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeMerge.test.ts#L147): _(error)_ Missing trailing comma

### triple-equals

- [`lib/element/codeOfConduct.ts:64`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/element/codeOfConduct.ts#L64): _(error)_ == should be ===

### typedef

- [`lib/api/reporting.ts:100`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/api/reporting.ts#L100): _(error)_ expected call-signature: 'runReports' to have a typedef
- [`lib/feature/DefaultFeatureManager.ts:100`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/DefaultFeatureManager.ts#L100): _(error)_ expected call-signature: 'features' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:32`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TsLintFeature.ts#L32): _(error)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:34`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TsLintFeature.ts#L34): _(error)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:36`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TsLintFeature.ts#L36): _(error)_ expected call-signature: 'apply' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:42`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TsLintFeature.ts#L42): _(error)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:44`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TsLintFeature.ts#L44): _(error)_ expected member-variable-declaration: 'p' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:61`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TsLintFeature.ts#L61): _(error)_ expected parameter: 'path' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:33`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TypeScriptVersionFeature.ts#L33): _(error)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:35`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TypeScriptVersionFeature.ts#L35): _(error)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:37`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TypeScriptVersionFeature.ts#L37): _(error)_ expected call-signature: 'apply' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:43`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TypeScriptVersionFeature.ts#L43): _(error)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TypeScriptVersionFeature.ts#L45): _(error)_ expected call-signature: 'derive' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:55`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TypeScriptVersionFeature.ts#L55): _(error)_ expected call-signature: 'relevanceTest' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:59`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/feature/domain/TypeScriptVersionFeature.ts#L59): _(error)_ expected call-signature: 'necessityTest' to have a typedef
- [`lib/routes/wellKnownReporters.ts:102`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/routes/wellKnownReporters.ts#L102): _(error)_ expected call-signature to have a typedef
- [`lib/setIdeals.ts:28`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/setIdeals.ts#L28): _(error)_ expected call-signature: 'setIdeals' to have a typedef
- [`lib/tree/partitioner.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/lib/tree/partitioner.ts#L45): _(error)_ expected call-signature: 'rate' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected parameter: 'q' to have a typedef
- [`test/tree/treeBuilder.test.ts:69`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeBuilder.test.ts#L69): _(error)_ expected call-signature to have a typedef
- [`test/tree/treeBuilder.test.ts:69`](https://github.com/atomist-blogs/org-visualizer/blob/32686d9b90d84ba0bbb23ed6afad4dbec42cf603/test/tree/treeBuilder.test.ts#L69): _(error)_ expected parameter: 'ars' to have a typedef

[atomist:code-inspection:api=@atomist/atomist-sdm]

**Comment by slimslenderslacks** [comment]
Issue closed because branch `api` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `api` was deleted.
