### ISSUE TITLE
Code Inspection: npm audit on scatter

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#3]
### graphql-code-generator:>=0

- _(error)_ [Insecure Default Configuration](https://npmjs.com/advisories/834) _No fix is currently available. Consider using an alternative module until a fix is made available._ 
  - `graphql-code-generator:0.16.1`: 
    - `@atomist/automation-client>graphql-code-generator`

### handlebars:<=4.0.13 || >=4.1.0 <4.1.2

- _(error)_ [Prototype Pollution](https://npmjs.com/advisories/755) _For handlebars 4.1.x upgrade to 4.1.2 or later.
For handlebars 4.0.x upgrade to 4.0.14 or later._ 
  - `handlebars:4.0.12`: 
    - `typedoc>handlebars`

### js-yaml:<3.13.0

- _(warn)_ [Denial of Service](https://npmjs.com/advisories/788) _Upgrade to version 3.13.0._ 
  - `js-yaml:3.12.0`: 
    - `@atomist/automation-client>graphql-code-generator>graphql-config>js-yaml`
    - `@atomist/sdm-core>@kubernetes/client-node>js-yaml`
    - `@atomist/uhura>@kubernetes/client-node>js-yaml`
    - `tslint>js-yaml`
  - `js-yaml:3.12.1`: 
    - `@atomist/automation-client>graphql-code-generator>js-yaml`

### js-yaml:<3.13.1

- _(error)_ [Code Injection](https://npmjs.com/advisories/813) _Upgrade to version 3.13.1._ 
  - `js-yaml:3.12.0`: 
    - `@atomist/automation-client>graphql-code-generator>graphql-config>js-yaml`
    - `@atomist/sdm-core>@kubernetes/client-node>js-yaml`
    - `@atomist/uhura>@kubernetes/client-node>js-yaml`
    - `tslint>js-yaml`
  - `js-yaml:3.12.1`: 
    - `@atomist/automation-client>graphql-code-generator>js-yaml`

### marked:>=0.3.14 <0.6.2

- _(warn)_ [Regular Expression Denial of Service](https://npmjs.com/advisories/812) _Upgrade to version 0.6.2 or later._ 
  - `marked:0.4.0`: 
    - `typedoc>marked`

### static-eval:<=2.0.1

- _(warn)_ [Sandbox Breakout / Arbitrary Code Execution](https://npmjs.com/advisories/758) _Upgrade to version 2.0.2 or later._ 
  - `static-eval:2.0.0`: 
    - `@atomist/sdm-core>@kubernetes/client-node>jsonpath>static-eval`
    - `@atomist/uhura>@kubernetes/client-node>jsonpath>static-eval`

[atomist:code-inspection:scatter=@atomist/atomist-sdm]

**Comment by dansmithy** [comment]
Issue closed because branch `scatter` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `scatter` was deleted.
