### ISSUE TITLE
Code Inspection: Tslint on nortissej/local-spider

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#32]
### await-promise

- [`lib/feature/reportersAgainst.ts:77`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/reportersAgainst.ts#L77): _(error)_ Invalid 'await' of a non-Promise value.
- [`lib/setIdeals.ts:47`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/setIdeals.ts#L47): _(error)_ Invalid 'await' of a non-Promise value.

### max-line-length

- [`views/org.tsx:114`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/views/org.tsx#L114): _(warn)_ Exceeds maximum line length of 150

### no-console

- [`lib/analysis/offline/persist/PostgresProjectAnalysisResultStore.ts:191`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/analysis/offline/persist/PostgresProjectAnalysisResultStore.ts#L191): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/analysis/offline/spider/github/GitHubSpider.ts:113`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/analysis/offline/spider/github/GitHubSpider.ts#L113): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/analysis/offline/spider/local/LocalSpider.ts:58`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/analysis/offline/spider/local/LocalSpider.ts#L58): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/feature/repoTree.ts:87`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/repoTree.ts#L87): _(warn)_ Calls to 'console.log' are not allowed.
- [`lib/routes/orgPage.ts:206`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/orgPage.ts#L206): _(warn)_ Calls to 'console.log' are not allowed.
- [`views/org.tsx:26`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/views/org.tsx#L26): _(warn)_ Calls to 'console.log' are not allowed.

### no-duplicate-imports

- [`lib/routes/features.ts:27`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/features.ts#L27): _(error)_ Multiple imports from '@atomist/sdm-pack-fingerprints' can be combined into one.

### no-empty-interface

- [`views/sunburstQuery.tsx:3`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/views/sunburstQuery.tsx#L3): _(error)_ An empty interface is equivalent to `{}`.

### no-floating-promises

- [`lib/setIdeals.ts:51`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/setIdeals.ts#L51): _(error)_ Promises must be handled appropriately

### no-object-literal-type-assertion

- [`lib/routes/orgPage.ts:208`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/orgPage.ts#L208): _(error)_ Type assertion on object literals is forbidden, use a type annotation instead.
- [`test/spider/github/GithubSpider.test.ts:57`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L57): _(error)_ Type assertion on object literals is forbidden, use a type annotation instead.

### no-shadowed-variable

- [`lib/feature/reportersAgainst.ts:89`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/reportersAgainst.ts#L89): _(error)_ Shadowed name: 'fp'
- [`lib/feature/reportersAgainst.ts:100`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/reportersAgainst.ts#L100): _(error)_ Shadowed name: 'fp'
- [`lib/feature/reportersAgainst.ts:112`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/reportersAgainst.ts#L112): _(error)_ Shadowed name: 'fp'
- [`lib/routes/api.ts:67`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/api.ts#L67): _(error)_ Shadowed name: 'workspaceId'
- [`lib/routes/api.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/api.ts#L134): _(error)_ Shadowed name: 'workspaceId'
- [`lib/routes/orgPage.ts:211`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/orgPage.ts#L211): _(error)_ Shadowed name: 'displayIdeal'

### no-var-requires

- [`lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts:35`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/analysis/offline/persist/FileSystemProjectAnalysisResultStore.ts#L35): _(error)_ require statement not part of an import statement

### triple-equals

- [`lib/element/codeOfConduct.ts:64`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOfConduct.ts#L64): _(error)_ == should be ===

### typedef

- [`lib/element/codeOwnership.ts:69`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOwnership.ts#L69): _(error)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/element/codeOwnership.ts:71`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOwnership.ts#L71): _(error)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/element/codeOwnership.ts:73`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOwnership.ts#L73): _(error)_ expected call-signature: 'apply' to have a typedef
- [`lib/element/codeOwnership.ts:79`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOwnership.ts#L79): _(error)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/element/codeOwnership.ts:81`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOwnership.ts#L81): _(error)_ expected call-signature: 'derive' to have a typedef
- [`lib/element/codeOwnership.ts:91`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOwnership.ts#L91): _(error)_ expected call-signature: 'relevanceTest' to have a typedef
- [`lib/element/codeOwnership.ts:95`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/element/codeOwnership.ts#L95): _(error)_ expected call-signature: 'necessityTest' to have a typedef
- [`lib/feature/DefaultFeatureManager.ts:74`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/DefaultFeatureManager.ts#L74): _(error)_ expected call-signature: 'features' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:32`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TsLintFeature.ts#L32): _(error)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:34`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TsLintFeature.ts#L34): _(error)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:36`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TsLintFeature.ts#L36): _(error)_ expected call-signature: 'apply' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:42`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TsLintFeature.ts#L42): _(error)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:44`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TsLintFeature.ts#L44): _(error)_ expected member-variable-declaration: 'p' to have a typedef
- [`lib/feature/domain/TsLintFeature.ts:61`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TsLintFeature.ts#L61): _(error)_ expected parameter: 'path' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:33`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TypeScriptVersionFeature.ts#L33): _(error)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:35`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TypeScriptVersionFeature.ts#L35): _(error)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:37`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TypeScriptVersionFeature.ts#L37): _(error)_ expected call-signature: 'apply' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:43`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TypeScriptVersionFeature.ts#L43): _(error)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TypeScriptVersionFeature.ts#L45): _(error)_ expected call-signature: 'derive' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:55`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TypeScriptVersionFeature.ts#L55): _(error)_ expected call-signature: 'relevanceTest' to have a typedef
- [`lib/feature/domain/TypeScriptVersionFeature.ts:59`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/domain/TypeScriptVersionFeature.ts#L59): _(error)_ expected call-signature: 'necessityTest' to have a typedef
- [`lib/feature/repoTree.ts:40`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/repoTree.ts#L40): _(error)_ expected call-signature: 'without' to have a typedef
- [`lib/feature/repoTree.ts:58`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/feature/repoTree.ts#L58): _(error)_ expected call-signature: 'fingerprintsChildrenQuery' to have a typedef
- [`lib/routes/api.ts:114`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/api.ts#L114): _(error)_ expected call-signature: 'resolveFeatureNames' to have a typedef
- [`lib/routes/orgPage.ts:256`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/orgPage.ts#L256): _(error)_ expected parameter: 'req' to have a typedef
- [`lib/routes/wellKnownReporters.ts:102`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/routes/wellKnownReporters.ts#L102): _(error)_ expected call-signature: 'mapping' to have a typedef
- [`lib/setIdeals.ts:31`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/setIdeals.ts#L31): _(error)_ expected call-signature: 'setIdeals' to have a typedef
- [`lib/tree/partitioner.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/lib/tree/partitioner.ts#L45): _(error)_ expected call-signature: 'rate' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:123`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L123): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:134`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L134): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:153`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L153): _(error)_ expected parameter: 'q' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected call-signature to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected parameter: 't' to have a typedef
- [`test/spider/github/GithubSpider.test.ts:177`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/spider/github/GithubSpider.test.ts#L177): _(error)_ expected parameter: 'q' to have a typedef
- [`test/tree/treeBuilder.test.ts:68`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/tree/treeBuilder.test.ts#L68): _(error)_ expected call-signature: 'mapping' to have a typedef
- [`test/tree/treeBuilder.test.ts:68`](https://github.com/atomist-blogs/org-visualizer/blob/900a72b80bde383e611815ebf3cf02410b4620d2/test/tree/treeBuilder.test.ts#L68): _(error)_ expected parameter: 'ars' to have a typedef

[atomist:code-inspection:nortissej/local-spider=@atomist/atomist-sdm]

**Comment by cdupuis** [comment]
Issue closed because branch `nortissej/local-spider` was deleted.

**Comment by whostolebenfrog** [comment]
Issue closed because branch `nortissej/local-spider` was deleted.
