### ISSUE TITLE
Code Inspection: Tslint on nortissej/documentation-url

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#62]
### max-line-length

- [`lib/customize/features.ts:50`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/customize/features.ts#L50): _(warn)_ Exceeds maximum line length of 150

### no-console

- [`lib/routes/api.ts:83`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/api.ts#L83): _(warn)_ Calls to 'console.log' are not allowed.

### no-shadowed-variable

- [`lib/feature/reportersAgainst.ts:106`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/reportersAgainst.ts#L106): _(error)_ Shadowed name: 'name'
- [`lib/routes/api.ts:144`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/api.ts#L144): _(error)_ Shadowed name: 'fingerprints'
- [`lib/routes/api.ts:151`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/api.ts#L151): _(error)_ Shadowed name: 'data'
- [`lib/routes/api.ts:163`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/api.ts#L163): _(error)_ Shadowed name: 'fingerprints'
- [`lib/routes/api.ts:170`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/api.ts#L170): _(error)_ Shadowed name: 'data'

### typedef

- [`lib/element/codeOwnership.ts:65`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/element/codeOwnership.ts#L65): _(warn)_ expected call-signature: 'apply' to have a typedef
- [`lib/element/codeOwnership.ts:71`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/element/codeOwnership.ts#L71): _(warn)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/element/codeOwnership.ts:73`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/element/codeOwnership.ts#L73): _(warn)_ expected member-variable-declaration: 'extract' to have a typedef
- [`lib/feature/DefaultFeatureManager.ts:75`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/DefaultFeatureManager.ts#L75): _(warn)_ expected call-signature: 'features' to have a typedef
- [`lib/feature/node/TsLintFeature.ts:26`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/node/TsLintFeature.ts#L26): _(warn)_ expected member-variable-declaration: 'type' to have a typedef
- [`lib/feature/node/TsLintFeature.ts:36`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/node/TsLintFeature.ts#L36): _(warn)_ expected member-variable-declaration: 'displayName' to have a typedef
- [`lib/feature/node/TsLintFeature.ts:38`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/node/TsLintFeature.ts#L38): _(warn)_ expected member-variable-declaration: 'name' to have a typedef
- [`lib/feature/node/TsLintFeature.ts:40`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/node/TsLintFeature.ts#L40): _(warn)_ expected call-signature: 'apply' to have a typedef
- [`lib/feature/node/TsLintFeature.ts:46`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/node/TsLintFeature.ts#L46): _(warn)_ expected member-variable-declaration: 'p' to have a typedef
- [`lib/feature/node/TsLintFeature.ts:63`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/node/TsLintFeature.ts#L63): _(warn)_ expected parameter: 'path' to have a typedef
- [`lib/feature/repoTree.ts:41`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/repoTree.ts#L41): _(warn)_ expected call-signature: 'without' to have a typedef
- [`lib/feature/repoTree.ts:59`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/feature/repoTree.ts#L59): _(warn)_ expected call-signature: 'fingerprintsChildrenQuery' to have a typedef
- [`lib/routes/orgPage.ts:249`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/orgPage.ts#L249): _(warn)_ expected parameter: 'req' to have a typedef
- [`lib/routes/wellKnownReporters.ts:211`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/wellKnownReporters.ts#L211): _(warn)_ expected call-signature: 'mapping' to have a typedef
- [`lib/routes/wellKnownReporters.ts:364`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/routes/wellKnownReporters.ts#L364): _(warn)_ expected call-signature: 'featureGroup' to have a typedef
- [`lib/tree/partitioner.ts:45`](https://github.com/atomist-blogs/org-visualizer/blob/24f04264582dfb0d5625bab71225670ee8094bf0/lib/tree/partitioner.ts#L45): _(warn)_ expected call-signature: 'rate' to have a typedef

[atomist:code-inspection:nortissej/documentation-url=@atomist/atomist-sdm]

**Comment by slimslenderslacks** [comment]
Issue closed because branch `nortissej/documentation-url` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `nortissej/documentation-url` was deleted.
