### ISSUE TITLE
Code Inspection: npm audit on entropy

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#67]
### marked:>=0.3.14 <0.6.2

- _(warn)_ [Regular Expression Denial of Service](https://npmjs.com/advisories/812) _Upgrade to version 0.6.2 or later._ 
  - `marked:0.4.0`: 
    - `typedoc>marked`

[atomist:code-inspection:entropy=@atomist/atomist-sdm]

**Comment by dansmithy** [comment]
Issue closed because branch `entropy` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `entropy` was deleted.
