### ISSUE TITLE
Code Inspection: Tslint on branches

### ISSUE THREAD

**Issue by cdupuis** [atomist-blogs/org-visualizer#90]
### typedef

- [`lib/aspect/node/TsLintAspect.ts:41`](https://github.com/atomist-blogs/org-visualizer/blob/6bf1e2244483b693aa654d9086b44d9ad1d3441e/lib/aspect/node/TsLintAspect.ts#L41): _(warn)_ expected call-signature: 'apply' to have a typedef
- [`lib/element/codeOwnership.ts:70`](https://github.com/atomist-blogs/org-visualizer/blob/6bf1e2244483b693aa654d9086b44d9ad1d3441e/lib/element/codeOwnership.ts#L70): _(warn)_ expected call-signature: 'apply' to have a typedef
- [`lib/element/codeOwnership.ts:76`](https://github.com/atomist-blogs/org-visualizer/blob/6bf1e2244483b693aa654d9086b44d9ad1d3441e/lib/element/codeOwnership.ts#L76): _(warn)_ expected member-variable-declaration: 'fp' to have a typedef
- [`lib/element/codeOwnership.ts:78`](https://github.com/atomist-blogs/org-visualizer/blob/6bf1e2244483b693aa654d9086b44d9ad1d3441e/lib/element/codeOwnership.ts#L78): _(warn)_ expected member-variable-declaration: 'extract' to have a typedef
- [`lib/routes/wellKnownReporters.ts:166`](https://github.com/atomist-blogs/org-visualizer/blob/6bf1e2244483b693aa654d9086b44d9ad1d3441e/lib/routes/wellKnownReporters.ts#L166): _(warn)_ expected call-signature: 'mapping' to have a typedef
- [`lib/routes/wellKnownReporters.ts:319`](https://github.com/atomist-blogs/org-visualizer/blob/6bf1e2244483b693aa654d9086b44d9ad1d3441e/lib/routes/wellKnownReporters.ts#L319): _(warn)_ expected call-signature: 'aspectGroup' to have a typedef

[atomist:code-inspection:branches=@atomist/atomist-sdm]

**Comment by dansmithy** [comment]
Issue closed because branch `branches` was deleted.

**Comment by cdupuis** [comment]
Issue closed because branch `branches` was deleted.
