### ISSUE TITLE
Getting adequate git information shouldn't unduly slow cloning before analysis

### ISSUE THREAD

**Issue by johnsonr** [atomist-blogs/org-visualizer#96]
Possible approaches include:

- Introducing further cloning options in `automation-client`
- Having git aspects perform a fetch, if it's possible to make a shallow clone know about branches.

We need to support remote branch count and active committer aspects.

**Comment by jessitron** [comment]
waiting on: https://github.com/atomist/automation-client/pull/572

I could not find a way to get a shallow clone to fetch all branches from origin unless --no-single-branch is passed on clone.
